config/routes.rb
Rails.application.routes.draw do
  root "people#index"
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :quotes, dependent: :destroy


  validates :first_name, presence: true

  def full_name
    "#{self.last_name}, #{self.first_name}"
  end


end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.order(:last_name)
  end

  def show
    @person = Person.find(params[:id])
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def new
    @person = Person.new()
  end

  def create
    # @page = Page.new(params.require(:page).permit(:title, :author, :body))
    @person = Person.new(person_params)
    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def destroy
    @person = Person.find(params[:id]).destroy
    redirect_to people_path
  end

  private
  def person_params
    params.require(:person).permit(:first_name, :last_name, :age, :eye_color, :hair_color, :gender, :alive)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1> Edit Person Info </h1>
<hr />
<%= form_for @person do |f| %>

<%= f.label :first_name %>: 
<%= f.text_field :first_name %>
<br>
<%= f.label :last_name %>: 
<%= f.text_field :last_name %>
<br>
<%= f.label :age %>: 
<%= f.text_field :age %>
<br>
<%= f.label :hair_color %>:
<%= f.text_field :hair_color %>
<br>
<%= f.label :eye_color %>:
<%= f.text_field :eye_color %>
<br>
<%= f.label :gender %>:
<%= f.text_field :gender %>
<br>
<%= f.label :alive %> (true or false):
<%= f.text_field :alive %>
<br>
<br>
<%=f.submit%>


<%end%>

app/views/people/index.html.erb
<h1>Index of People</h1>
<hr />
<h2><%= link_to "Create New Person", new_person_path%></h2>
<% @people.each do |person| %>
<h2>  <%= person.last_name %>, <%= person.first_name %> </h2>
<ul>
<li> <%= link_to "Contact Details", person_path(person.id)%> </li>
<li> <%= link_to "Edit Contact", edit_person_path(person.id)%> </li>
<li> <%= link_to "Delete Contact", person_path(person.id), method: :delete %> </li>
</ul>
<%end%>
<p></p>

app/views/people/new.html.erb
<h1> New Person Form </h1>
<hr />
<%= form_for @person do |f| %>

<%= f.label :first_name %>: 
<%= f.text_field :first_name %>
<br>
<%= f.label :last_name %>: 
<%= f.text_field :last_name %>
<br>
<%= f.label :age %>: 
<%= f.text_field :age %>
<br>
<%= f.label :hair_color %>:
<%= f.text_field :hair_color %>
<br>
<%= f.label :eye_color %>:
<%= f.text_field :eye_color %>
<br>
<%= f.label :gender %>:
<%= f.text_field :gender %>
<br>
<%= f.label :alive %> (true or false):
<%= f.text_field :alive %>
<br>
<br>
<%=f.submit%> or <%=link_to "Back To Index", people_path%>


<%end%>

app/views/people/show.html.erb
<h1> <%= @person.full_name%> </h1>
<hr />
<h4>Age: <%= @person.age %> </h4>
<h4>Hair color: <%= @person.hair_color %> </h4>
<h4>Eye color: <%= @person.eye_color %> </h4>
<h4>Gender: <%= @person.gender %> </h4>
<h4>
<% if @person.alive == true %> 
Alive
<%else%>
Deceased
<%end%> </h4>

<h3> <%= link_to "Back To Index", people_path %> </h3>